name: "GitHub Pages build"

on:
  push:
    branches: [main]

jobs:
  frozen-flask:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
         fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - run: python -m venv venv/
      - run: python -m pip install -r pip-requirements.txt
      - run: git worktree add build ghpages
      - run: source venv/bin/activate
      - run: flask build
      - run: ls -r build/
      - run: |
          cd build/
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A --verbose
          git commit -m "Built flask site" --allow-empty
          git push
